In [1]:
import pandas as pd

In [2]:
print(pd.__version__)

3.0.2

### Pandas Data Structures
- Series: a one-dimensional labeled array holding data of any type such as integers, strings, Python objects etc. Think of it like a column in a table.
- DataFrame: a two-dimensional data structure that holds data like a two-dimension array or a table with rows and columns.

In [5]:
import numpy as np
s = pd.Series([1, 3, 5, np.nan, 6, 8])

In [6]:
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In pandas, np.nan stands for Not a Number. It is a special floating-point value inherited from the NumPy library and is used as the standard marker for missing or undefined data.

Conceptually, `np.nan` is equivalent to `None` and to `pd.NA` as they are all markers for the absence of a value although they all have their unique properties and ways of working with it.

In [22]:
df2 = pd.DataFrame(
    {
        "A": 1,
        "B": pd.Timestamp("20130102"),
        "C": pd.Series(1, list(range(4)), dtype="float32"),
        "D": np.array([3] * 4, dtype="int32"),
        "E": pd.Categorical(["test", "train", "test", "train"]),
        "F": "foo",
    }
)
df2

   A          B    C  D      E    F
0  1 2013-01-02  1.0  3   test  foo
1  1 2013-01-02  1.0  3  train  foo
2  1 2013-01-02  1.0  3   test  foo
3  1 2013-01-02  1.0  3  train  foo

In [19]:
student_data = {
    "Student_ID": [101, 102, 103],
    "Name": ["Lizzy", "Faith", "Tina"],
    "Program": ["DAF", "DAF", "SEF"],
    "Satisfaction": 1
}
df = pd.DataFrame(student_data)
df

   Student_ID   Name Program  Satisfaction
0         101  Lizzy     DAF             1
1         102  Faith     DAF             1
2         103   Tina     SEF             1

### Series Deep-dive

In [ ]:
phone_brands = ["Samsung", "Apple", "Pixel", "Nokia"]
# phone_brands = pd.Series(phone_brands)
phone_brands = pd.Series(phone_brands, index=['a', 'b', 'c', 'd'])
phone_brands
# phone_brands, phone_brands[0

**Question:** How do I print the item Samsung?

In [40]:
calories = {"day1": 420, "day2": 380, "day3": 390}

myvar = pd.Series(calories)
myvar

day1    420
day2    380
day3    390
dtype: int64

In [41]:
sr = pd.Series(
    [1, 2, 3, 4, 5, 6],
    index=['Q', 'W', 'E', 'R', 'T', 'Y'],
    name="Number List"
)
sr

Q    1
W    2
E    3
R    4
T    5
Y    6
Name: Number List, dtype: int64

We can locate a row using the `loc` or `iloc` methods. The loc is used with labls and iloc is used with positions. Hence the names `loc` -> location and `iloc` -> integer location.

Here are some examples below:

In [42]:
sr.loc["Q":"R"]

Q    1
W    2
E    3
R    4
Name: Number List, dtype: int64

In [43]:
sr.iloc[0:3]

Q    1
W    2
E    3
Name: Number List, dtype: int64

In [60]:
sr2 = [1, 2, 3]
sr2 = pd.Series(sr2)

In [62]:
sr2.index = [11, 12, 13]
sr2

11    1
12    2
13    3
dtype: int64

In [66]:
sr2.loc[11]

np.int64(1)

In [68]:
sr2.iloc[0]

np.int64(1)

#### Exercise
Add the numbers 30, 45, and 80 to the `sr` series.

### DataFrames Deep-dive

In [69]:
df = pd.DataFrame({
    "Age": [21,19,22,20,23,23,21],
    "Sex": ["M","M","F","M","F","F","M"],
    "GPA": [3.45,2.98,3.72,2.87,3.90,4.00,1.90]
}, index=["James", "Mark", "Rebecca", "David", "Lucy", "Judy", "Johnny"])

df

         Age Sex   GPA
James     21   M  3.45
Mark      19   M  2.98
Rebecca   22   F  3.72
David     20   M  2.87
Lucy      23   F  3.90
Judy      23   F  4.00
Johnny    21   M  1.90

In [70]:
df.head()

         Age Sex   GPA
James     21   M  3.45
Mark      19   M  2.98
Rebecca   22   F  3.72
David     20   M  2.87
Lucy      23   F  3.90

In [71]:
df.tail()

         Age Sex   GPA
Rebecca   22   F  3.72
David     20   M  2.87
Lucy      23   F  3.90
Judy      23   F  4.00
Johnny    21   M  1.90

What do you notice?

Calling our DataFrame or Series with .head() will return the first rows of our dataset. Passing an int to this function will return the first nth rows, but will return the first 5 rows as default (if you don't pass a number). However, if you want to access the last rows, you can use the .tail() function.

#### Exercises
1. Using loc and iloc, return the first 3 rows of data.
2. Using the `.head()` method, return the first 2 rows of data.
3. What will be the output of `df.loc["David":"Johnny", ["Age", "Sex"]]`?
4. If we can pick a row, then we can also remove. What will be the output of: `df.drop(["James", "Mark"])`?
5. Run this line and explain what it does: `df["GPA"] >= 3.0`
6. How do i get the data for the students who have a GPA of 3.0 and below?
7. Create a new column bases on the GPA called `hasPassed`. It should be of type `boolean` and return True if the GPA is 3.0 and above and False otherwise.

In [74]:
df["Sex"]

James      M
Mark       M
Rebecca    F
David      M
Lucy       F
Judy       F
Johnny     M
Name: Sex, dtype: str

In [75]:
df.rename(columns={"Sex": "Gender"})

         Age Gender   GPA
James     21      M  3.45
Mark      19      M  2.98
Rebecca   22      F  3.72
David     20      M  2.87
Lucy      23      F  3.90
Judy      23      F  4.00
Johnny    21      M  1.90

In [76]:
df

         Age Sex   GPA
James     21   M  3.45
Mark      19   M  2.98
Rebecca   22   F  3.72
David     20   M  2.87
Lucy      23   F  3.90
Judy      23   F  4.00
Johnny    21   M  1.90

In [78]:
df = df.rename(columns={"Sex": "Gender"})
df

         Age Gender   GPA
James     21      M  3.45
Mark      19      M  2.98
Rebecca   22      F  3.72
David     20      M  2.87
Lucy      23      F  3.90
Judy      23      F  4.00
Johnny    21      M  1.90

In [88]:
pd.Series?
# or pd.Series??

In [83]:
pd.DataFrame?
# or pd.DataFrame??

#### Exercise 1 - The Manual Spreadsheet
1. Create a DataFrame called df_fruits using this data:
Fruit: Apple, Banana, Cherry
Quantity: 10, 15, 20
2. Print the DataFrame to see how pandas added the Index (0, 1, 2) automatically.

#### Exercise 2 - Selecting your Columns
1. Using the df_fruits you just made, select only the "Quantity" column and save it to a variable called q.
2. Type type(q) to confirm it is a pandas.core.series.Series.
3. Calculate the sum of that column using q.sum().

#### Exercise 3 - Adding a constant column
1. Add a new column to your df_fruits called "Store".
2. Set its value to "Main Street".
(Hint: You only need to type the string once; pandas will fill all rows for you!)

#### Exercise 4 - Quick Inspection
1. Run `df_fruits.head(2)`. What does it show you?
2. Run `df_fruits.info()`. What do you see?